spring:
  application:
    name: APZ-CLOUD-EUREKA-API
  # security
  security:
    user:
      name: admin
      password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/
