server:
  port: 10020

spring:
  application:
    name: APZ-CLOUD-OPEN-API
    # security
  security:
    user:
      name: admin
      password: 123456
  profiles:
    active: dev

eureka:
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${apz.cloud.eureka.server-name}/eureka/

---
spring:
  profiles: dev
apz:
  cloud:
    eureka:
      server-name: eureka.hcbxwy.com

---
spring:
  profiles: prod
apz:
  cloud:
    eureka:
      server-name: localhost:8761
